/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proga.CPUsimLite;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hani
 */
public class MainMemory extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form tableGUI
     */
    public MainMemory() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Addesss(Hex)", "Content(Hex)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Memory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMemory().setVisible(true);
            }
        });
    }

    public void insertCode(List<String> code) {
        for (int i = 0; i < code.size(); i++) {

            //Set opcodes
            String[] words = code.get(i).replaceAll("[;,]", "")
                    .replace("SUB", "57").replace("DEC", "62")
                    .replace("INC", "56").replace("MOV", "45").replace("END", "68")
                    .replace("INP", "33").replace("OUT", "48").replace("BNZ", "28").replace("SKZ", "41")
                    .replace("NEGATE", "67").replace("ADD", "58").replace("MULTIPLY", "115")
                    .replace("PUSH", "23").replace("POP", "24").replace("SKIP", "29").replace("SKIPZ", "30")
                    .split("\\s+");

            //Convert opcode from decimal to binary
            switch (words.length) {
                case 1:
                    //zero operand
                    words[0] = intToBinary(Integer.parseInt(words[0]), 8);
                    break;
                case 2:
                    //one operand
                    words[0] = intToBinary(Integer.parseInt(words[0]), 6);
                    break;
                case 3:
                    //two operands
                    words[0] = intToBinary(Integer.parseInt(words[0]), 6);
                    break;
                default:
                    break;
            }
            
            //Set operands
            for (int j = 1; j < words.length; j++) {

                if (words[j].contains("#")) { //Immediate  Addressing Mode
                    int value = Integer.parseInt(words[j].substring(1, words[j].length()));
                    words[j] = "00" + intToBinary(value, 8);

                } else if (words[j].contains("(")) {  //Indirect Addressing Mode                
                    //Register Indirect
                    if (words[j].contains("R")) {
                        int regNum = Integer.parseInt(words[j].substring(2, 3));
                        words[j] = "11" + intToBinary(regNum, 8);

                    } //Memory Indirect
                    else {
                        int memoryAdd = Integer.parseInt(words[j].substring(1, words[j].indexOf(")")));
                        words[j] = "01" + intToBinary(memoryAdd, 8);
                    }
                } else if (words[j].contains("R")) { //Register Addressing Mode
                    int regNum = Integer.parseInt(words[j].substring(1, 2));
                    words[j] = "10" + intToBinary(regNum, 8);

                } else {

                    JOptionPane.showMessageDialog(null, "Error in addressing Mode in line " + i);

                }

            }

            String instCode = String.join("", words);

            Object[] rowData = new Object[]{
                Integer.toHexString(i),
                Integer.toHexString(Integer.parseInt(instCode, 2))
            };
            model.addRow(rowData);

        }

    }

    public String getContent(String add) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(add)) {
                return model.getValueAt(i, 1).toString();
            }
        }
        return null;
    }

    public void insertContent(String add, String content) {
        boolean exist = false;
        int location = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(add)) {
                exist = true;
                location = i;
                break;
            }
        }
        if (exist) {
            model.removeRow(location);

            Object[] rowData = new Object[]{
                add,
                content
            };
            model.insertRow(location, rowData);

        } else {

            Object[] rowData = new Object[]{
                add,
                content
            };
            model.addRow(rowData);
        }
    }

    public static String intToBinary(int n, int numOfBits) {
        String binary = "";
        for (int i = 0; i < numOfBits; ++i, n /= 2) {
            switch (n % 2) {
                case 0:
                    binary = "0" + binary;
                    break;
                case 1:
                    binary = "1" + binary;
                    break;
            }
        }

        return binary;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
